### ISSUE TITLE
Where can we find the find the .fc6-1 files?

### ISSUE THREAD

**Issue by mourad1081** [WaqasSultani/AnomalyDetectionCVPR2018#35]
Hello, 

First of all, I want to thank you for your great article. It gives amazing results and I have decided for my master thesis to work on anomaly detection in CCTV videos as well thanks to you. Currently, I am trying to replicate your work.

However, I always run out of memory when I try to generate the features of the videos using C3D. Even with my GTX 970 4GO VRAM and a batch-size of 1... And it has been like that for month now... I don't have the money to buy a better GPU.

I am then asking for an archive where one can find the features of the videos (fc6-1 files) or the txt files containing the 32 segments of each videos for all the dataset.

Is it possible please? Thank you!

**Comment by WaqasSultani** [comment]
Hi Mourad,
Sorry, I don't have those features. However, you don't have to use C3D. It's just the video features that we used in our paper.  You can use I3D (https://github.com/deepmind/kinetics-i3d/blob/master/i3d.py) or Multifiber network (https://github.com/cypw/PyTorch-MFNet). I believe you should be able to compute them.
I got an email from someone that he used I3D instead of C3D and got better results.
I believe I3D or Multifiber network could be easily run on freely available GPU (Google Collab).
Good luck with your MS thesis.

Best,

**Comment by mourad1081** [comment]
Hello, thank you very much for your answer. I'll dig further on what you suggest me.

Thanks,

**Comment by Anirudh58** [comment]
Hi @mourad1081 

Just a suggestion if you are still trying to use C3D, I had a similar running out of memory problem since I did not have any powerful GPU. 
You can however, evade this issue by explicitly mentioning that you want to use only CPU. 
The script inside c3d_sport1m_feature_extraction_video.sh should be changed as follows. 

`GLOG_logtosterr=1 ../../build/tools/extract_image_features.bin prototxt/c3d_sport1m_feature_extractor_video.prototxt conv3d_deepnetA_sport1m_iter_1900000 -1 10 100000 prototxt/output_video_list.txt fc6-1`

The '-1' mentions that you want to use only CPU. 

It will however be very slow, obviously. Took me almost 4 days to extract FC6 features from 1600 videos.

**Comment by mourad1081** [comment]
Hello @Anirudh58 ,

Thank you for your suggestion. I have tried that workaround some weeks ago but it was too slow (I had to let my computer run for a hundred days 24/7). 

Fortunately, a friend brought me a GTX 1080 and everything works fine regarding C3D. It took roughly one hour to process several hours of video.
